exp_name: '55555'
model_path: ./vqvae_weights/0/best.pt
data_dir: ./vqvae_data/testapi
hidden_size: 512
k: 1024
batch_size: 2
negative_sample_number: 10
num_workers: 6
device: cpu
moco_model_path: ./weights/0/best.pth.tar
n_clusters: 4
defect_img_folder: ./dataset/55555/defect_img
defect_mask_folder: ./dataset/55555/defect_mask
result_name: futa_no_elf_c8
