aug_plus: true
batch_size: 4
cos: true
data_path: /mnt/backups/kevin/fastapi_pcl/train_pcl_api/code/data
dist_backend: nccl
dist_url: tcp://localhost:10001
epochs: 20
exp_dir: weights
gpu: 0
low_dim: 128
lr: 0.03
mlp: true
moco_m: 0.999
momentum: 0.9
multiprocessing_distributed: true
num_cluster: '2'
pcl_r: 4096
print_freq: 1000
rank: 0
resume: ''
schedule:
- 120
- 160
seed: true
start_epoch: 0
temperature: 0.2
warmup_epoch: 10
weight_decay: 0.0001
workers: 2
world_size: 1
exp_name: '123'
pretrained: null
image_root: ''
negative_samples_path: /mnt/backups/kevin/fastapi_pcl/train_pcl_api/code/data
